name: uninest_flutter
description: UniNest - Your all-in-one digital campus hub for students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  http: ^1.1.2
  supabase_flutter: ^2.0.3
  
  # UI Components
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  
  # Payment
  razorpay_flutter: ^1.3.6
  
  # Chat & Real-time
  web_socket_channel: ^2.4.0
  
  # Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
